version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nome_do_banco
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
